### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by aharris88** [kentcdodds/prettier-eslint#1]
Is there a CLI for this? I tried can use prettier in vim because it is a cli tool, but I'm not sure how to use prettier-eslint in vim.

**Comment by kentcdodds** [comment]
Not yet, but I really want one! Do you wanna build it?!

**Comment by aharris88** [comment]
I would like to, but I'm not sure how. Would it be a part of this repo or a separate repo?

**Comment by kentcdodds** [comment]
I'd prefer to make it a separate repo. `prettier-eslint-cli` seems like a good module name :) Should be pretty small I think. I recommend looking into `yargs`...

... You know what, I can scaffold a project pretty quickly and easily. How would you like me to just get it scaffolded out and then give you write permissions?

**Comment by aharris88** [comment]
Sounds good.

**Comment by kentcdodds** [comment]
Alrighty, you should have access to push to https://github.com/kentcdodds/prettier-eslint-cli

I've squatted on `prettier-eslint-cli` on npm. Once we've got something to release, I'll setup automatic releasing with semantic-release and travis. I'm looking forward to seeing what you've come up with!

**Comment by kentcdodds** [comment]
@aharris88, I want to use the CLI on a project. Have you started already? If not, I'm going to go ahead and build it now.

**Comment by aharris88** [comment]
I haven't started. Go ahead. 👍
