### ISSUE TITLE
peerDependencies?

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/prettier-eslint#3]
Right now we ship `prettier` and `eslint` as dependencies to the project. But we should probably find the most relevant packages instead. Maybe use the first available version:

1. local `node_modules`
2. global `node_modules`
3. Our own `node_modules`

Any ideas/suggestions are welcome! (This should solve https://github.com/kentcdodds/prettier-eslint-atom/issues/5)

**Comment by kentcdodds** [comment]
ping @gyandeeps, any ideas here?

**Comment by gyandeeps** [comment]
I think this issue will help us respect the version of `eslint` used by the user and not the one shipped with this package?
Then (assuming we are using npm >= 3), we can always use the local node_modules `eslint` period. That means user have to always have a dependency on eslint. If they dont then (npm > 3) will install `eslint` inside node_modules folder (based on this package dependency). Worst case we can grab it from inside our own node_modules folder.

Why are we discussing global?

**Comment by kentcdodds** [comment]
> Why are we discussing global?

👏  I'd rather not think about global.

The one case where things can get a little tricky is in the [`prettier-eslint-atom`](https://github.com/kentcdodds/prettier-eslint-atom) plugin as well as [`prettier-eslint-cli`](https://github.com/kentcdodds/prettier-eslint-cli). We need to figure out which `prettier` and `eslint` to use for those. I think that `prettier-eslint` needs to expose a mechanism for specifying the path to `prettier` and `eslint` to use.

Shouldn't be too challenging I think. Just something on `options` [like `disableLog` is right now](https://github.com/kentcdodds/prettier-eslint/blob/master/src/index.js#L7) and instead of importing `prettier` and `eslint` at the module level, we'll do a `require` statement when they're needed. Thoughts?
