### ISSUE TITLE
Add sillyLogs

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/prettier-eslint#7]
So we can get everything we need for debugging. From https://github.com/kentcdodds/prettier-eslint-cli/pull/1

> We should probably expose a way for you to log out the `eslintConfig` and `prettierOptions` that are used for the formatting. Would you be interested in doing that? Would probably just need another option (like `sillyLogs`) and add the `console.log` [here](https://github.com/kentcdodds/prettier-eslint/blob/master/src/index.js#L39) that includes the `eslintConfig` and `prettierOptions` (maybe put it in a separate function and just call it there... Wanna try?

@edm00se's going to give this a try tonight (hopefully)

**Comment by edm00se** [comment]
I gave things a first pass in PR #8, but am having trouble getting the test to play nicely 😕.
